### ISSUE TITLE
(fabric) Permission denied: b'../charts'", "path": "../charts/catools/certs"

### ISSUE THREAD

**Issue by uqix** [hyperledger/bevel#1931]
https://github.com/hyperledger/bevel/blob/bbdf9312c34a9ffece7cadf9480be1de7849f056/platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml#L64

I needed to add `{{ playbook_dir }}` to make it work:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/10142314/165091395-a1c269ca-b33e-4a8b-97df-209909048905.png">

**Comment by uqix** [comment]
Same problem here:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/10142314/165091616-72ebb0fc-932e-4812-aae8-221a95be1db6.png">

**Comment by uqix** [comment]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/10142314/165091768-deb3873d-3833-4cfb-8067-af10e8b57366.png">

**Comment by uqix** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/10142314/165091965-34e61184-3839-40fa-91f5-6f11cd5a607b.png">

**Comment by uqix** [comment]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/10142314/165092070-5363de66-e0b9-4de5-9f2b-2374cfe57f5f.png">

**Comment by suvajit-sarkar** [comment]
Hi @uqix thanks for raising this issue. It seems that you have already fixed the issue, it would be great if you could create a PR.

**Comment by jagpreetsinghsasan** [comment]
Hi @uqix 
Thanks for this detailed check.
It's always a great idea to have absolute parameterized paths (like the ones mentioned in this solution) instead of some relative ones.
But my concern is, whether these absolute paths gonna work well with the molecule tests, because with the molecules tests, the {{ playbook_dir }} var changes resulting in some tests failing.
Can this be verified once?

**Comment by uqix** [comment]
molecules is kind of beyond my skill set, anyway, I'll look into it when available.
