### ISSUE TITLE
On-premise deployment of Bevel for Hyperledger Fabric blockchain infrastructure

### ISSUE THREAD

**Issue by gokulsan** [hyperledger/bevel#2048]
Is it possible to deploy Bevel on premise for the automation of Hyperledger Fabric blockchain infrastructure? What are the configurations in Bevel required to support this requirement. I have checked the sample [configuration files]([examples/supplychain-app/configuration/samples/network-fabricv2.yaml]). It is only mentioning a set of cloud providers such as AWS, Azure and GCP.

**Comment by sownak** [comment]
@gokulsan Yes, it is possible to deploy Fabric using Bevel on on-premise, you need to have a on-prem Kubernetes cluster and an on-prem Hashicorp Server. You will need to add a Storage class template as per [this guide](https://hyperledger-bevel.readthedocs.io/en/latest/operations/adding_new_storageclass.html) for your on-prem Kubernetes cluster. 
Our documents only mention Cloud providers because we do not use on-prem for our development or test environments.

**Comment by gokulsan** [comment]
Thank you so much @sownak for sharing the requirements and steps. Please let me proceed further in this direction.
